import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Oswald, Lato } from "next/font/google";
import "./globals.css";
import FloatingNavbar from "@/components/navbar";
import Footer from "@/components/footer";

const oswald = Oswald({
  variable: "--font-oswald-sans",
  subsets: ["latin"],
});

const lato = Lato({
  weight: ["400", "700"],
  variable: "--font-lato-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${oswald.variable} antialiased`}>
        <FloatingNavbar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
